### ISSUE TITLE
.gitignore is inside .gitignore folder

### ISSUE THREAD

**Issue by mateusfccp** [ssdaniel96/TarefinhaCAvaliacao#2]
`.gitignore` should be at the root level of the repository. If it is placed inside a folder, it will only ignore the files relative to that folder. Being so, the `.gitignore` file inside the `.gitignore` folder is doing literally nothing.

This can also be seen by the fact that `*.o` files and `.vscode` has been committed to the repository, even being described in the `.gitignore`.

**Comment by ssoaresdaniel** [comment]
Yes, thanks, I didn't know why.
